apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parkshare-dev
resources:
  - namespace.yaml
  - ../../base
images:
  - name: docker.io/darkata/parkshare-backend
    newTag: dev
  - name: docker.io/darkata/parkshare-frontend
    newTag: dev
patches:
  - path: patch-ingress-hosts.yaml
  - path: patch-replicas.yaml
