apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parkshare-backend
spec:
  rules:
    - host: api.parkshare.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: parkshare-backend
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parkshare-frontend
spec:
  rules:
    - host: parkshare.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: parkshare-frontend
                port:
                  name: http
